export const AppImages = {
  back: require('./back/icon.png'),
  'focusing-to-take-a-picture': require('./focusing-to-take-a-picture/icon.png'),
  'arrow-left': require('./arrow-left/icon.png'),
  bolt: require('./bolt/icon.png'),
  check: require('./check/icon.png'),
  download: require('./download/icon.png'),
  'google-logo': require('./google-logo/icon.png'),
  home: require('./home/icon.png'),
  language: require('./language/icon.png'),
  logo: require('./logo/icon.png'),
  scan: require('./scan/icon.png'),
  share: require('./share/icon.png'),
  user: require('./user/icon.png'),
  'user-profile': require('./user-profile/icon.png'),
  card: require('./card/icon.png'),
  'default-avatar': require('./default-avatar/icon.png'),
};
